export const ActionTypes = {
  SET_MOVIES: "SET_MOVIES",
  SELECTED_MOVIE: "SELECTED_MOVIE",
  REMOVE_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE",
  LIKE_MOVIE:"LIKE_MOVIE",
  DISLIKE_MOVIE:"DISLIKE_MOVIE",
  FILTER_MOVIES_CAT:"FILTER_MOVIES_CAT",
};
